import type { Conversation, FeedPost, Momento } from '@/types/domain'

export const MOCK_POSTS: FeedPost[] = [
  {
    id: 'post-001',
    userId: 'creator-001',
    userName: 'Luna Estrela',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=luna&backgroundColor=7C3AED',
    userUsername: '@lunaestela',
    isVerified: true,
    content:
      'Nova sessao de fotos exclusiva. Para os meus assinantes Diamond, conteudo especial aguardando voces no vault! #OnlyDay #Premium',
    media: [{ type: 'image', url: 'https://picsum.photos/seed/luna1/800/600' }],
    isLocked: false,
    likes: 1243,
    comments: 87,
    shares: 34,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hashtags: ['OnlyDay', 'Premium', 'Exclusivo'],
  },
  {
    id: 'post-002',
    userId: 'creator-002',
    userName: 'Rafael Ouro',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rafael&backgroundColor=6D28D9',
    userUsername: '@rafaelouro',
    isVerified: true,
    content:
      'Bastidores do meu novo projeto musical. Quem quer ver o processo criativo? Reage com sol para eu postar mais!',
    isLocked: false,
    likes: 892,
    comments: 156,
    shares: 67,
    isLiked: true,
    isSaved: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hashtags: ['Musica', 'Bastidores'],
  },
  {
    id: 'post-003',
    userId: 'creator-003',
    userName: 'Sofia Dark',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sofia&backgroundColor=5B21B6',
    userUsername: '@sofiadark',
    isVerified: true,
    content: 'Conteudo exclusivo para assinantes',
    media: [{ type: 'image', url: 'https://picsum.photos/seed/sofia1/800/600' }],
    isLocked: true,
    price: 29.9,
    likes: 2341,
    comments: 412,
    shares: 89,
    isLiked: false,
    isSaved: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    hashtags: ['Exclusivo', 'Premium'],
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-001',
    userId: 'creator-001',
    userName: 'Luna Estrela',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=luna&backgroundColor=7C3AED',
    userUsername: '@lunaestela',
    isVerified: true,
    isPremium: true,
    lastMessage: 'Amei sua mensagem!',
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    unreadCount: 2,
    intimacyScore: 73,
    isOnline: true,
    messages: [
      {
        id: 'msg-001',
        senderId: 'creator-001',
        receiverId: 'user-001',
        content: 'Oi! Obrigada por assinar meu plano Diamond!',
        type: 'text',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'msg-002',
        senderId: 'user-001',
        receiverId: 'creator-001',
        content: 'Seu conteudo e incrivel! Quando vem o proximo?',
        type: 'text',
        timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'msg-003',
        senderId: 'creator-001',
        receiverId: 'user-001',
        content: 'Amei sua mensagem!',
        type: 'text',
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        isRead: false,
      },
      {
        id: 'msg-004',
        senderId: 'creator-001',
        receiverId: 'user-001',
        content: 'Conteudo exclusivo para voce!',
        type: 'media',
        mediaUrl: 'https://picsum.photos/seed/locked1/400/400',
        isLocked: true,
        price: 19.9,
        timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
        isRead: false,
      },
    ],
  },
  {
    id: 'conv-002',
    userId: 'creator-002',
    userName: 'Rafael Ouro',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rafael&backgroundColor=6D28D9',
    userUsername: '@rafaelouro',
    isVerified: true,
    isPremium: true,
    lastMessage: 'Vou lancar algo especial essa semana!',
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    intimacyScore: 45,
    isOnline: false,
    messages: [
      {
        id: 'msg-005',
        senderId: 'creator-002',
        receiverId: 'user-001',
        content: 'Vou lancar algo especial essa semana!',
        type: 'text',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        isRead: true,
      },
    ],
  },
]

export const MOCK_MOMENTOS: Momento[] = [
  {
    id: 'mom-001',
    userId: 'creator-001',
    userName: 'Luna Estrela',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=luna&backgroundColor=7C3AED',
    userUsername: '@lunaestela',
    isVerified: true,
    media: 'https://picsum.photos/seed/luna-mom1/400/700',
    mediaType: 'image',
    isLocked: false,
    viewCount: 1823,
    duration: 5000,
    expiresAt: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mom-002',
    userId: 'creator-002',
    userName: 'Rafael Ouro',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rafael&backgroundColor=6D28D9',
    userUsername: '@rafaelouro',
    isVerified: true,
    media: 'https://picsum.photos/seed/rafael-mom1/400/700',
    mediaType: 'image',
    isLocked: false,
    viewCount: 934,
    duration: 7000,
    expiresAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mom-003',
    userId: 'creator-003',
    userName: 'Sofia Dark',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sofia&backgroundColor=5B21B6',
    userUsername: '@sofiadark',
    isVerified: true,
    media: 'https://picsum.photos/seed/sofia-mom1/400/700',
    mediaType: 'image',
    isLocked: true,
    price: 9.9,
    dailyFreeCount: 3,
    viewCount: 5621,
    duration: 6000,
    expiresAt: new Date(Date.now() + 16 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
]
